### ISSUE TITLE
Invalid user upgrade

### ISSUE THREAD

**Issue by book777** [paymentwall/module-xenforo#8]
Hello! I have a problem with XenForo 1.5.7

Exception: Invalid user upgrade - paymentwall.php:24

array(3) {
  ["url"] => string(317) "https://my[...].su/paymentwall.php?uid=15&goodsid=resource_purchase%7C15%7Ce809e%7C135&slength=&speriod=&type=0&ref=t1461690695&is_test=1&sign_version=3&custom=15%7C135%7Cresource_purchase%7C15%2C1461690688%2C58e0ac1[...]0c1cc0&sig=2[...]0b1275a9c5fd53aa513228680957eff9b3b"
  ["_GET"] => array(10) {
    ["uid"] => string(2) "15"
    ["goodsid"] => string(30) "resource_purchase|15|e809e|135"
    ["slength"] => string(0) ""
    ["speriod"] => string(0) ""
    ["type"] => string(1) "0"
    ["ref"] => string(11) "t1461690695"
    ["is_test"] => string(1) "1"
    ["sign_version"] => string(1) "3"
    ["custom"] => string(79) "15|135|resource_purchase|15,1461690688,58e0ac165cd5a10d225831d59914b894700c1cc0"
    ["sig"] => string(64) "278c207b6b6996ae6035be95062760b1275a9c5fd53aa513228680957eff9b3b"
  }
  ["_POST"] => array(0) {
  }
}

**Comment by pwSupport** [comment]
Hi Book777, 
Thanks for reaching out,

Can you please mail to devsupport@paymentwall.com with the title "[XenForo] - _Title of your issue_" and provide us more information about this error?

Regards,
Paymentwall Team
